# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # tests:
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [16.x]

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: ${{ matrix.node-version }}

  #     - name: Install dependencies
  #       run: npm install
  #       working-directory: ./user-service

  #     - name: Run tests
  #       run: npm run test
  #       working-directory: ./user-service
  deploy-user-service:
    if: github.event_name =='push'

    runs-on: ubuntu-latest
    # needs: [tests]
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_HUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
        run: docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_PASSWORD}}

      - name: Build the Docker image
        run: docker build ./user-service --file ./user-service/Dockerfile --tag nadiiavol/user-service:latest

      - name: Docker Push
        run: docker push nadiiavol/user-service:latest

  deploy-chat-service:
    if: github.event_name == 'push'

    runs-on: ubuntu-latest
    # needs: [tests]

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_HUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
        run: |
          docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_PASSWORD}}

      - name: Build the Docker image
        run: docker build ./chat-service --file ./chat-service/Dockerfile --tag nadiiavol/chat-service:latest

      - name: Docker Push
        run: docker push nadiiavol/chat-service

  deploy-chat-client:
    if: github.event_name == 'push'

    runs-on: ubuntu-latest
    # needs: [tests]

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_HUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
        run: |
          docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_PASSWORD}}

      - name: Build the Docker image
        run: docker build ./client-app --file ./client-app/Dockerfile --tag nadiiavol/client-app:v2

      - name: Docker Push
        run: docker push nadiiavol/client-app

  # deploy-auth-middleware:
  #   if: github.event_name == 'push'

  #   runs-on: ubuntu-latest
  #   # needs: [tests]

  #   strategy:
  #     matrix:
  #       node-version: [16.x]

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Docker login
  #       env:
  #         DOCKER_USER: ${{secrets.DOCKER_HUB_USERNAME}}
  #         DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
  #       run: |
  #         docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_PASSWORD}}

  #     - name: Build the Docker image
  #       run: docker build ./facebook-oauth-middleware --file ./facebook-oauth-middleware/Dockerfile --tag nadiiavol/facebook-oauth-middleware:latest

  #     - name: Docker Push
  #       run: docker push nadiiavol/facebook-oauth-middleware
